# 问题
当我们要一次处理大量并发请求，比如100条，这会对浏览器造成很大的压力，所以我们需要一种方法来处理这些请求，使得浏览器不会因为处理这些请求而卡死。因此，我们可以实现一个方法，每次处理三个请求，当三个请求都处理完毕后，再处理下三个请求，直到所有请求都处理完毕，并将结果返回。

(关于浏览器在超过最大http连接数之后会怎么做，是一个值得深挖的问题，同时这个问题也可以延申到后端的限流处理)

（这个问题是一个经过扩展的问题，原本的问题比较限定，这里我把问题扩展了一下，使得问题更加具有普遍性）

参考:
https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser


# 问题分析
1. 我们可以假设每个异步请求是一个异步函数，假如不是异步函数，比如是给定了参数以及发送的位置，我们也可以通过包装使其成为异步请求函数
2. 我们需要明确返回的方式，这里假定一个比较常见的场景，也就是我们需要返回一个`Promise<[any]>`，数组中的每个元素是每个请求的返回值，假如遇到了拒绝请求，我们返回最先拒绝的原因,并且放弃后面的请求。
3. 接着，我们要明确请求的顺序，这里先假定是按照请求给定的顺序返回结果，也就是说，如果请求的顺序是`[1,2,3,4,5,6,7,8,9]`，那么返回的结果就是`[1,2,3,4,5,6,7,8,9]`。
4. 至此，我们可以将问题明确为，实现一个如下函数

```typescript
function handleRequest(requests: [() => Promise<any>], limit: number = 3): Promise<any[]> {
    // 以同时最大并发3个请求的方式发送请求，当所有请求完成返回结果
}
```

# 解

采用自顶向下分析法，也就是我们先设计一个足够好用的顶层抽象，再一步步明确实现细节，最后完全实现我们的函数。

1. 设计一个`RequestQueue`类，其有一个`push(): Promise<any>`方法，当我们用`push`向这个队列添加一个异步函数时,如果请求队列中有任何一个`reject`，就直接返回`Promise.reject`，假如队列中的异步函数数量小于`limit`，那么`push`返回的`Promise`就会立刻`resolve`，假如队列中的异步函数数量大于等于`limit`，那么`await push`就会阻塞当前执行环境的异步函数, 并在任何一个请求完成后，根据请求成功与否`resolved`或`reject`。
2. 我们再设计一个方法`RequestQueue.prototype.result()`，其将所有结果以`Promise<any[]>`的方式返回, 如果遇到了拒绝请求，就会返回一个`Promise.reject`。
3. 利用该类的实例，我们可以轻易的实现顶层函数`handleRequest`：

```typescript
class RequestQueue {
    queue = [];
    limit: number;
    result =an'yany
    constructor(limit) {
        // ...
    }
    push(request: () => Promise<any>): Promise<null> {
        // ...
    }
    result(): Promise<any[]> {
        // ...
    }
}

function handleRequest(requests: [() => Promise<any>], limit: number = 3): Promise<any[]> {
    return new Promise((resolve, reject)=>{
        const queue = new RequestQueue(limit);
        for (const request of requests) {
            await queue.push(request).catch(reject);
        }
        resolve(queue.result()); // 假如我们resolve了一个 Promise.rejct，其状态也会变成 reject
    });
}
```

4. 确定顶层的实现合理后，我们可以开始实现`RequestQueue`类，我们可以先实现`push`及`result`方法，其实现如下：

```typescript
class RequestQueue {
    //...
    push(request: () => Promise<any>): Promise<null> {
        return new Promise(async (resolve, reject) => {
            if(this.queue.length >= this.limit) {
                // 如果之前的请求有任何一个失败，就返回该`reject`
                // 如果之前的请求中有任何一个resolve了，就代表有位置空出来了，我们就可以继续
                await Promise.race(this.queue).catch(reject);
            }
            const p = request();
            p.then(res => this.result.push(res));
            this.queue.push(p);
            // 这里的 resolve 不代表请求成功，只代表下一个新的异步请求可以进来了
            resolve();
        });
    }
    result(): Promise<any[]> {
        return Promise.all(this.queue).then(() => this.result);
    }
}
```